version: 2.1
jobs:
  build-android:
    docker:
      - image: cimg/android:2023.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build Android
          command: npm run android
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-android
